### ISSUE TITLE
Restructure project to follow standard Maven Standard Directory Layout 

### ISSUE THREAD

**Issue by aSemy** [Kotlin/kotlinx-knit#48]
Currently Knit does not follow the [Standard Directory Layout](https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html)

https://github.com/Kotlin/kotlinx-knit/blob/c4e77da4dfc4a863c71f7d09fe7c566d2ee39936/build.gradle.kts#L49-L53

While this reduces the number of directories that the project has, I find it makes it much more difficult to navigate as the new files don't follow the conventions that most projects use, and it's unclear what files are within which subproject.

**Comment by qwwdfsad** [comment]
We are moving towards complete the opposite: https://youtrack.jetbrains.com/issue/KTIJ-20411/Project-wizard-should-provide-an-option-to-create-compact-directory-layout-common-package-prefix and https://youtrack.jetbrains.com/issue/KTIJ-23274/First-party-support-of-compact-directory-layout-common-package-prefix, so closing as "won't fix".

Tickets have pretty self-describing rationale I do hope

**Comment by aSemy** [comment]
Oh okay, that's a bit weird and confusing. IntelliJ automatically collapses them so it's not a big difference. But okay. 

Anyway, implementing buildSrc convention plugins means there's no need for nested subprojects, which would probably help just as much, and make it clear about what files belong to which project.

I'll see if I can update the PR #51  to something like this?

```
.
└── kotlinx-knit/
    ├── kotlinx-knit-core/
    │   ├── src/
    │   │   ├── Knit.kt
    │   │   └── ...
    │   ├── test/
    │   │   └── ...
    │   ├── testResources/
    │   │   └── testdata/
    │   │       └── ...
    │   └── build.gradle.kts
    └── kotlinx-knit-gradle/
        ├── main/
        │   └── KnitPlugin.kt
        ├── resources/
        │   └── knit.properties
        ├── test/
        ├── testResources/
        ├── testFixtures/
        ├── testFixturesResources/
        └── build.gradle.kts
```
