### ISSUE TITLE
Using knit with latest dokka doesn't work

### ISSUE THREAD

**Issue by Ifropc** [Kotlin/kotlinx-knit#53]
Knit use 1.6 version of dokka. When adding to project with dokka v1.7 it doesn't work.

**Comment by IgnatBeresnev** [comment]
@qwwdfsad I'll check it for 1.8.0

**Comment by IgnatBeresnev** [comment]
Oh, just noticed #54 - so it does work, but not when the versions are misaligned? What was the problem?

**Comment by Ifropc** [comment]
Yes, that's what I meant. Sorry for confusion
